### PR TITLE
Wait methods fixes

### LINKED ISSUE #121: WaitAny method doesn't check if `wait` has failed
Method `Connector::WaitAny` does not check return code of the net provider when calling its `wait` method. Hence, it won't stop in the case of internal error.

### LINKED ISSUE #133: Methods `waitCount` and `waitAll` wait even if all futures are ready
It happens because we firstly call `NetProvider::wait` and only then we check for ready futures.

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
This patchset fixes some bugs with the Connector `wait*` methods.

Closes #121
closes #133

### CODE REVIEW

File: src/Client/Connector.hpp [hunk 1]
```diff
@@ -283,6 +278,10 @@ Connector<BUFFER, NetProvider>::waitAll(Connection<BUFFER, NetProvider> &conn,
 		}
 		if (finish)
 			return 0;
+		if (m_NetProvider.wait(timer.timeLeft()) != 0) {
+			conn.setError(std::string("Failed to poll: ") + strerror(errno), errno);
+			return -1;
+		}
```
Comment (drewdzzz) [inline src/Client/Connector.hpp:284]: It looks weird to me that there is no check of readiness after the timeout is expired - it would be nice to return TimeOut error only if it's really the case.

Also, since we don't decode responses after the `wait` here, we will have to decode them on the next `Connector::wait*(...)` call, and it will reduce actual wait time (we will spend some time from timeout to decode previously received responses).

File: test/ClientTest.cpp [hunk 2]
```diff
@@ -1324,6 +1332,30 @@ test_wait(Connector<BUFFER, NetProvider> &client)
 	fail_unless(result.header.sync == static_cast<int>(f1));
 	fail_unless(result.header.code == 0);
 
+#ifdef __linux__
+	TEST_CASE("waitAny internal wait failure (gh-121)");
+	static constexpr double LONG_SLEEP_TIME = 2;
```
Comment (drewdzzz) [inline test/ClientTest.cpp:1337]: Couldn't we reduce sleep time?

File: test/ClientTest.cpp [hunk 3]
```diff
@@ -1324,6 +1332,30 @@ test_wait(Connector<BUFFER, NetProvider> &client)
...
+	sigaction(SIGUSR1, &act, nullptr);
+	auto &&signal_thread = std::thread([tid] {
+		sleep(LONG_SLEEP_TIME / 2);
+		pthread_kill(tid, SIGUSR1);
+	});
+	fail_unless(!client.waitAny().has_value());
+	fail_unless(client.waitAny().has_value());
+	fail_unless(conn.futureIsReady(f));
+	response = conn.getResponse(f);
+	fail_unless(response.has_value());
```
Comment (drewdzzz) [inline test/ClientTest.cpp:1354]: It would be nice to check that all wait functions handle errors if it's easy to do so.

Comment (CuriousGeorgiy) [reply test/ClientTest.cpp]: Done.

**Review by drewdzzz — APPROVED** [review]
Thank you for the patch! Glad to see the connector is thriving!
LGTM.
