### PR TITLE
Wait methods fixes [part 2]

### LINKED ISSUE #51: `Connector::waitAny` cannot handle scenario when all connections are dead
The `Connector` does not have access to the connections it is associated with, so it is impossible to detect a scenario when all connections are dead and a timeout is not specified, hence the `Connector` will simply hang in this loop:
https://github.com/tarantool/tntcxx/blob/6420c7e2abe3dc93128e427b43aa75abce0e94cc/src/Client/Connector.hpp#L256-L257

Simple reproducer:
```c++
#include "src/Client/Connector.hpp"
#include "src/Buffer/Buffer.hpp"

const char *inet_address = "127.0.0.1";
int port = 3301;

using Buf_t = tnt::Buffer<16 * 1024>;
using Net_t = LibevNetProvider<Buf_t, DefaultStream>;

int
main()
{
	pid_t pid = fork();
	if (pid < 0) {
		perror("fork failed");
		return EXIT_FAILURE;
	} else if (pid == 0) {
		int sock = ::socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
		if (sock < 0) {
			perror("socket failed");
			return EXIT_FAILURE;
		}

		struct sockaddr_in sock_address = {
			.sin_family = AF_INET,
			.sin_port = htons(port),
		};
		if (::inet_aton(inet_address, &sock_address.sin_addr) != 1) {
			perror("inet_aton failed");
			return EXIT_FAILURE;
		}

		if (::bind(sock, reinterpret_cast<const struct sockaddr *>(&sock_address),
			sizeof(sockaddr)) != 0) {
			perror("bind failed");
			return EXIT_FAILURE;
		}

		if (::listen(sock, 1) != 0) {
			perror("listen failed");
			return EXIT_FAILURE;
		}

		int accepted_sock = ::accept(sock, nullptr, nullptr);
		if (accepted_sock < 0) {
			perror("accept failed");
			return EXIT_FAILURE;
		}

		char buf[1];
		if (::read(accepted_sock, buf, sizeof(buf)) < 0) {
			perror("read failed");
			return EXIT_FAILURE;
		}

		close(accepted_sock);
		return EXIT_SUCCESS;
	}

	Connector<Buf_t, Net_t> client;
	Connection<Buf_t, Net_t> conn(client);

	int rc = client.connect(conn, {
		.address = inet_address,
		.service = std::to_string(port),
	});
	if (rc != 0) {
		std::cerr << conn.getError().msg << std::endl;
		return EXIT_FAILURE;
	}

	rid_t ping = conn.ping();
	assert(client.waitAny() == std::nullopt);
	assert(!conn.futureIsReady(ping));

	client.close(conn);
}
```

### LINKED ISSUE #132: Method `Connector::waitAny` polls only not decoded connections
If the connection was already decoded, `waitAny` won't handle it at all.

### LINKED ISSUE #140: Connector internals should always store connection implementation pointers rather than connection objects
In our client tests we assume that a destructed connection is automatically closed:
https://github.com/tarantool/tntcxx/blob/a3d0414a8a072c37adac09e477ee9143a8a0a1dd/test/ClientTest.cpp#L238-L262

However, the connection destructor only unreferences the underlying connection implementation rather than closing it:
https://github.com/tarantool/tntcxx/blob/a3d0414a8a072c37adac09e477ee9143a8a0a1dd/src/Client/Connection.hpp#L397-L401

This is done to make connections copyable. If there were only user connection objects, the connection destructors would eventually trigger connection closure (when the connection implementation has no references left and it gets destroyed). But, currently, the LibevNetProvider uses connection objects internally:
https://github.com/tarantool/tntcxx/blob/a3d0414a8a072c37adac09e477ee9143a8a0a1dd/src/Client/LibevNetProvider.hpp#L53-L64

Rather than using connection implementations like the EpollNetProvider:
https://github.com/tarantool/tntcxx/blob/a3d0414a8a072c37adac09e477ee9143a8a0a1dd/src/Client/EpollNetProvider.hpp#L119-L124

For the LibevNetProvider this means that connections will never get closed automatically, since there will always be an internal connection object.

However, it seems reasonable to rely on the fact that the lifetime of all connections used in the connector internals is tied to the user's connection objects. Hence, we should always store connection implementations rather than connection objects to avoid superfluous referencing.

### LINKED ISSUE #142: `close` of closed or faulty connection causes assertion failure
Consider this trivial snippet:
```c++
#include "../src/Client/Connector.hpp"

using Buf_t = tnt::Buffer<16 * 1024>;
using Net_t = LibevNetProvider<Buf_t, DefaultStream>;

int
main()
{
	Connector<Buf_t, Net_t> client;
	Connection<Buf_t, Net_t> conn(client);
	client.close(conn);
}
```

It crashes with the following assertion:
```console
Assertion failed: (!conn.strm.has_status(SS_DEAD)), function close, file Connector.hpp, line 171.
```

However, the `SS_DEAD` status can be set for a multitude of reasons without the connection being closed or connected. For instance, if the connection was lost or a `send`/`recv` failed:
https://github.com/tarantool/tntcxx/blob/a3d0414a8a072c37adac09e477ee9143a8a0a1dd/src/Client/UnixPlainStream.hpp#L137-L142

https://github.com/tarantool/tntcxx/blob/a3d0414a8a072c37adac09e477ee9143a8a0a1dd/src/Client/UnixPlainStream.hpp#L119

### LINKED ISSUE #147: Connection `close` leaks connections
When `close`ing a connection, we do not erase it from the `m_ReadyToSend` and `m_ReadyToDecode` sets:
https://github.com/tarantool/tntcxx/blob/8e009e81a6e9a5924eed302e9a7cf652a2ba9110/src/Client/Connector.hpp#L184-L190

This causes all connections that have pending requests to be leaked.

### LINKED ISSUE #150: `ClientMultiThreadTest` is flaky on MacOS
The `ClientMultiThreadTest` test often fails on the CI for MacOS with the following ouput:
```shell
13: ERROR: Failed to connect: Operation now in progress
13: ERROR: Failed to connect to 127.0.0.1:3301
13: Test failed: rc == 0 is false at /Users/runner/work/tntcxx/tntcxx/test/ClientMultithreadTest.cpp:122 in test operator()
13: Assertion failed: (false), function operator(), file ClientMultithreadTest.cpp, line 122.
13: ERROR: Failed to connect: Operation now in progress
13: ERROR: Failed to connect to 127.0.0.1:3301
13: Test failed: rc == 0 is false at /Users/runner/work/tntcxx/tntcxx/test/ClientMultithreadTest.cpp:122 in test operator()
13: Assertion failed: (false), function operator(), file ClientMultithreadTest.cpp, line 122.
13/13 Test #13: ClientMultithread.test ...........Subprocess aborted***Exception:   3.21 sec
ERROR: Failed to connect: Operation now in progress
ERROR: Failed to connect to 127.0.0.1:3301
Test failed: rc == 0 is false at /Users/runner/work/tntcxx/tntcxx/test/ClientMultithreadTest.cpp:122 in test operator()
Assertion failed: (false), function operator(), file ClientMultithreadTest.cpp, line 122.
ERROR: Failed to connect: Operation now in progress
ERROR: Failed to connect to 127.0.0.1:3301
Test failed: rc == 0 is false at /Users/runner/work/tntcxx/tntcxx/test/ClientMultithreadTest.cpp:122 in test operator()
Assertion failed: (false), function operator(), file ClientMultithreadTest.cpp, line 122.
```

### LINKED ISSUE #151: `connect` timeout gets masked out by irrelevant error
Consider this trivial snippet with a `0` timeout:
```c++
#include "../src/Client/Connector.hpp"

using Buf_t = tnt::Buffer<16 * 1024>;
using Net_t = LibevNetProvider<Buf_t, DefaultStream>;

int
main()
{
	Connector<Buf_t, Net_t> client;
	Connection<Buf_t, Net_t> conn(client);
	struct ConnectOptions conn_opts{
		.address = "127.0.0.1",
		.service = "3301",
		.connect_timeout = 0,     		
	};
	client.connect(conn, conn_opts);
}
```

However, in the logs instead of a timeout error you will see:
```shell
ERROR: Failed to connect: Operation now in progress
ERROR: Failed to connect to 127.0.0.1:3301
```

### LINKED ISSUE #152: Anti-pattern free functions on `ConnectionImpl` and `Connection`
Currently, we have a bunch of free functions on ConnectionImpl and 
Connection, such as `hasSentBytes`, `hasNotRecvBytes`, `hasDataToSend`, 
`hasDataToDecode`, etc:
https://github.com/tarantool/tntcxx/blob/2184427552ea427098ca1c893fb40789aa4059a2/src/Client/Connection.hpp#L485-L604

All of them have a `ConnectionImpl` or `Connection`
as an argument. This is an anti-pattern, and these functions need to be 
encapsulated in the corresponding classes.

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
This patchset performs a major refactoring of the client code to replace all internal `Connection` usage  with `ConnectionImpl`, and fixes several related bugs.

Closes #51
Closes #132
Closes #140
Closes #142
Closes #147
Closes #150
Closes #151
Closes #152

### CODE REVIEW

File: src/Client/Connector.hpp [hunk 1]
```diff
@@ -82,13 +82,14 @@ class Connector
 		      size_t feature_count, int timeout = -1);
 	std::optional<Connection<BUFFER, NetProvider>> waitAny(int timeout = -1);
 	////////////////////////////Service interfaces//////////////////////////
-	void readyToDecode(const Connection<BUFFER, NetProvider> &conn);
-	void readyToSend(const Connection<BUFFER, NetProvider> &conn);
-	void finishSend(const Connection<BUFFER, NetProvider> &conn);
+	void readyToDecode(ConnectionImpl<BUFFER, NetProvider> *conn);
+	void readyToSend(ConnectionImpl<BUFFER, NetProvider> *conn);
+	void readyToSend(Connection<BUFFER, NetProvider> &conn);
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/Client/Connector.hpp:87]: Yes, the `Connection<BUFFER, NetProvider> &conn` overload is extensively relied upon by the `Connection` class in its DML methods, so I decided to keep it.

File: src/Client/Connection.hpp [hunk 2]
```diff
@@ -124,7 +124,7 @@ template<class BUFFER, class NetProvider>
 ConnectionImpl<BUFFER, NetProvider>::~ConnectionImpl()
 {
 	assert(refs == 0);
-	if (!strm.has_status(SS_DEAD)) {
+	if (strm.get_fd() != -1) {
```
Comment (drewdzzz) [inline src/Client/Connection.hpp:130]: Nit: We rely here that closed connection always had `fd` equal to `-1`. We should describe it in `UnixStream` class (to fixate this behavior) or introduce new `stem.is_closed()` method.

File: src/Client/Connector.hpp [hunk 3]
```diff
@@ -354,9 +360,22 @@ template<class BUFFER, class NetProvider>
...
 Connector<BUFFER, NetProvider>::waitAny(int timeout)
 {
+	if (m_Connections.empty()) {
+		LOG_DEBUG("waitAny() called on connector without connections");
+		return std::nullopt;
+	}
 	Timer timer{timeout};
 	timer.start();
 	while (m_ReadyToDecode.empty()) {
+		bool any_conn_has_no_err = false;
```
Comment (drewdzzz) [inline src/Client/Connector.hpp:374]: Nit: wouldn't `has_alive_conn` be better? Too many logical negations with this name :)

File: src/Client/Connector.hpp [hunk 4]
```diff
@@ -354,9 +360,22 @@ template<class BUFFER, class NetProvider>
...
+		for (auto *conn : m_Connections) {
+			if (!conn->hasError())
+				any_conn_has_no_err = true;
```
Comment (drewdzzz) [inline src/Client/Connector.hpp:377]: I believe we should `break` here.

File: src/Client/Connector.hpp [hunk 5]
```diff
@@ -364,6 +364,10 @@ Connector<BUFFER, NetProvider>::waitAny(int timeout)
 		LOG_DEBUG("waitAny() called on connector without connections");
 		return std::nullopt;
 	}
+	for (auto *conn : m_Connections) {
```
Comment (drewdzzz) [inline src/Client/Connector.hpp:367]: I think `waitAny` still should trigger net provider to send pending requests (`m_NetProvider.wait(0)`).

File: src/Client/Connection.hpp
Comment (drewdzzz) [inline src/Client/Connection.hpp:1]: Shouldn't this change be tested somehow?

**Review by drewdzzz — COMMENTED** [review]
Thank you for the patch! I believe it improves connector usability quite a lot.

File: src/Client/Connector.hpp (hunk 5 above)
Comment (CuriousGeorgiy) [reply src/Client/Connector.hpp]: > But, IMHO, all wait methods should trigger connector to send pending requests (or we should send them right on operation).

I don't think you are right here. We should try to minimize the number of system calls, where possible, because system calls cause context switches and kernel- to user- space transition. This is exactly what this patch is trying to do.

Instead, you propose to add an unconditional system call on each `wait` method call, even when it is not necessary and a user has something to process.

Moreover, doing this system call may be useless in the case when a user does not have any other pending requests.

> Until you've processed all 10 responses, no new requests will be sent, so you'll observe latency spike after you're done with those 10 responses.

I think the problem you describe should be solved the other way around: APIs that create requests should actively send them rather than postponing the sends to `wait` method calls.

File: src/Client/Connection.hpp [hunk 6]
```diff
@@ -471,73 +487,79 @@ template<class BUFFER, class NetProvider>
...
 {
-	return impl->outBuf;
+	return impl->getOutBuf();
 }
 
-template<class BUFFER, class NetProvider>
+template <class BUFFER, class NetProvider>
 void
-hasSentBytes(Connection<BUFFER, NetProvider> &conn, size_t bytes)
+hasSentBytes(ConnectionImpl<BUFFER, NetProvider> *conn, size_t bytes)
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/Client/Connection.hpp]: I agree, I have opened #152 and encapsulated all free functions into `ConnectionImpl` and `Connection`.

File: src/Client/Connector.hpp (hunk 5 above)
Comment (drewdzzz) [reply src/Client/Connector.hpp]: Feel free to resolve after reading it.
